version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  api:
    container_name: api
    depends_on:
      - mysql
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app/api
    entrypoint: ["sh", "entrypoint.sh"]
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
    entrypoint: ["sh", "entrypoint.sh"]

